### ISSUE TITLE
can't pass the configuration check

### ISSUE THREAD

**Issue by ohhmyladygaga** [hekm77/homeassistant-config#1]
home assistant 0.96.4
system log:

File "/config/custom_components/xiaomi_gateway_alarm/__init__.py", line 7
    <!DOCTYPE html>
    ^
SyntaxError: invalid syntax

**Comment by hekm77** [comment]
@ohhmyladygaga 
The empty file should be named `__init__.py`

**Comment by hekm77** [comment]
@ohhmyladygaga 
Read the [instruction](https://github.com/hekm77/homeassistant-config/tree/master/custom_components/xiaomi_gateway_alarm)
