### ISSUE TITLE
SwitchDevice is deprecated, modify XiaomiMiioGenericDevice to extend SwitchEntity

### ISSUE THREAD

**Issue by lolfonfire** [hekm77/homeassistant-config#10]
Hi,

I've been using your custom component for months now.
Yesterday Home Assisant v0.110.0 was released.
Since then I see this error message when I reboot Home Assistant:
[homeassistant.components.switch] SwitchDevice is deprecated, modify XiaomiMiioGenericDevice to extend SwitchEntity

They have been fixing related things for official integrations. 
But they won't fix custom components of course.
Is there anything I can do to fix this error?

This is my configuration.yaml:
![image](https://user-images.githubusercontent.com/50797554/82559171-6bc57800-9b6f-11ea-9c07-cc68b99bfb0f.png)

**Comment by hekm77** [comment]
Hi @lolfonfire 
The [Xiaomi miio Alarm Control Panel](https://www.home-assistant.io/integrations/alarm_control_panel.xiaomi_miio/) has been added to Home Assistant 0.110
I think it's better to use official integration.
The custom component will be removed.

**Comment by lolfonfire** [comment]
Hi @hekm77,

I must have overlooked it in the changelog.
I've removed your component and can confirm the official integration works.
Thanks for your help and the compoment which I've been using for months!
![image](https://user-images.githubusercontent.com/50797554/82563159-d3cb8c80-9b76-11ea-8460-0a476bbad7b2.png)
