### ISSUE TITLE
Integration with Gateway 3 lumi.gateway.mgl03

### ISSUE THREAD

**Issue by fiyors** [hekm77/homeassistant-config#12]
Hi hekm77,

I have problem with gateway lumi.gateway.mgl03 ? Do you know if this is compatible ?

![image](https://user-images.githubusercontent.com/67486161/101470670-94179700-3946-11eb-9fa8-7ed1a2c3f5a8.png)

Thanks.

**Comment by hekm77** [comment]
Hi @fiyors, you can test the [official](https://www.home-assistant.io/integrations/xiaomi_miio/#supported-xiaomi-gateway-models) integration
