### ISSUE TITLE
Add 'version' key in the manifest file for custom integration 'xiaomi_gateway_alarm'.

### ISSUE THREAD

**Issue by davidmateos** [hekm77/homeassistant-config#13]
Home Assistant will required in the 2021.6 version that all custom integration include a  'version' key in the manifest file
See HA log message:

> Logger: homeassistant.loader
> Source: loader.py:786
> First occurred: 4:11:03 PM (1 occurrences)
> Last logged: 4:11:03 PM
> 
> No 'version' key in the manifest file for custom integration 'xiaomi_gateway_alarm'. As of Home Assistant 2021.6, this integration will no longer be loaded. Please report this to the maintainer of 'xiaomi_gateway_alarm'

Could you add it to the  'xiaomi_gateway_alarm' component

**Comment by hekm77** [comment]
Hi @davidmateos 
The component will not be supported.
Use the [Xiaomi Gateway](https://www.home-assistant.io/integrations/xiaomi_miio/#supported-xiaomi-gateway-models
)  integration.

**Comment by davidmateos** [comment]
That works. Thanks for the advise @hekm77
