### ISSUE TITLE
error in HA 0.97.0 :(

### ISSUE THREAD

**Issue by RRozga** [hekm77/homeassistant-config#2]
**log:** "Integration xiaomi_gateway_alarm not found when trying to verify its switch platform."
**path for custom components:** /config/custom_components/xiaomi_gateway_alarm/switch.py and /config/custom_components/xiaomi_gateway_alarm/__ init __.py
**configuration.yaml:**
switch:
  - platform: xiaomi_gateway_alarm
    name: Xiaomi Gateway Alarm
    host: 192.168.1.99
    token: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx _(not KEY, right?)_

**Comment by hekm77** [comment]
@RRozga 
No, this is not the key.
You can get a token from MiHome App
![222](https://user-images.githubusercontent.com/22895433/62804593-0592cb80-baee-11e9-91e2-457aab74e3da.png)

Is the developer mode enabled?

**Comment by RRozga** [comment]
sure. Token is correct.

**Comment by hekm77** [comment]
@RRozga 
Ok. Try it.
I've added a [manifest.json](https://github.com/hekm77/homeassistant-config/tree/master/custom_components/xiaomi_gateway_alarm/)
Copy this file to same folder `<config_dir>/custom_components/xiaomi_gateway_alarm/`

**Comment by RRozga** [comment]
added manifest.json
nothing changed
