### ISSUE TITLE
Invalid config for [switch.xiaomi_gateway_alarm]

### ISSUE THREAD

**Issue by RicVinie** [hekm77/homeassistant-config#3]
Hi, thanks for this component. i was looking for something like this long time ago.
I have issue with the config.

Configuration invalid
Invalid config for [switch.xiaomi_gateway_alarm]: length of value must be at least 32 for dictionary value @ data['token']. Got 'xxxxxxxxxxxxxxxx'. (See ?, line ?). Please check the docs at https://home-assistant.io/components/switch.xiaomi_gateway_alarm/

what i am doing wrong?

**Comment by RicVinie** [comment]
the token is the same as the key of the gateway?

**Comment by hekm77** [comment]
Hi @RicVinie 
See https://github.com/hekm77/homeassistant-config/issues/2#issuecomment-520039672

**Comment by RicVinie** [comment]
Thanks, its working :)

Best regards
