### ISSUE TITLE
How to get notification off alarm in telegram

### ISSUE THREAD

**Issue by RicVinie** [hekm77/homeassistant-config#4]
Hi, is there a way to make automation off the alarm activation in telegram?

Thanks for the excelent component
Best regards

**Comment by hekm77** [comment]
Hi @RicVinie 
I don't know, unfortunately.
I do not use Telegram in Home Assistant.

**Comment by RicVinie** [comment]
How can you see that the alarm was triggered if you're away from home?

**Comment by hekm77** [comment]
This component can only arm/disarm the Xiaomi Gateway.
The ringtone, volume, and arming delay are configurable in the MiHome App.
Notification of a triggered alarm can be obtained by setting up automation in the MiHome App.

**Comment by RicVinie** [comment]
I only asked that, because the mihome app got several problems and sometimes doesnt sync in time.
And home assistant never failed one notification.

Best regards, continue the good work ;)
