### ISSUE TITLE
image reader_png

### ISSUE THREAD

**Issue by thetux07** [hekm77/homeassistant-config#6]
hello, 
il love your skin,
where have you find images for background cards ?
i would like another image ( diner room) and ( network)
it's possible ?
thank you
regards

**Comment by hekm77** [comment]
Hey.
I use free monocolor icons 512x512px and PS to process them.

https://www.flaticon.com
https://www.freepik.com

If you give me the link, I'll try to make icons.

**Comment by thetux07** [comment]
thank you very much !!
can you make me this 3 icones ? i don't have photoshop :(
https://www.flaticon.com/free-icon/chef_483841?term=kitchen&page=1&position=8
https://www.freepik.com/free-icon/computers-network-interface-symbol_735203.htm#page=1&query=network&position=8
https://www.freepik.com/free-icon/studio-desk-with-two-drawers-computer-monitor-it_718539.htm#page=1&query=desk&position=4

thank you so much for your help ! :):)

**Comment by hekm77** [comment]
I added to the www/bg_card_icons/ folder

**Comment by thetux07** [comment]
perfect thank so much !!:):)
