### ISSUE TITLE
Way easier method to get token

### ISSUE THREAD

**Issue by starkillerOG** [hekm77/homeassistant-config#7]
Hi @hekm77,
Thank you verry much for the awesom xiaomi_gateway_alarm custom_component.
I saw that you linked this document: [Retrieving the Access Token](https://www.home-assistant.io/integrations/vacuum.xiaomi_miio/#retrieving-the-access-token) to get the Token.
Actually all those options sound very difficult and require some old version of the app.
So I just tryed the develepor mode of the gateway and even in the latest app 5.6.46 (january 2020) the token is just there in plain text.

I use:
gateway model: lumi.gateway.v3
gateway firmware_version: 1.4.1_175
gateway hardware_version: MW300
Android app (Samsung Galaxy S8) version: 5.6.46

steps to get there:

1. Install the Xiaomi Home app
2. Sign In/make an account
3. Make sure you set your region to: Mainland China (Seems to be the longest line with Chines characters) under settings -> Region - (not sure if this is aqtually required, language can defenetly be set on English).
4. Select your Gateway in Xiaomi Home app
5. Then the 3 dots at the top right of the screen
6. Then click on about
7. Tap the version number (Plug-in version 2.77.1 as of January 2020) at the bottom of the screen repeatedly
8. You should now see 2 extra options listed in English, this means you enabled developer mode. [if not try all steps again!]
9. Under "Hub info" there is quite some text in json format, this includes the "token" that you need.

**Comment by starkillerOG** [comment]
@hekm77 could you update the readme for future users?

**Comment by hekm77** [comment]
Hey @starkillerOG 
Glad to hear someone's using the component.
Thank you for the addition.
In this [issue,](https://github.com/hekm77/homeassistant-config/issues/5#issuecomment-562877783) I gave a link to the instruction.
I'll add it to the README.

**Comment by starkillerOG** [comment]
@hekm77 yes I saw that insturction, but that is more difficult than the one I posted just now.

**Comment by hekm77** [comment]
@starkillerOG, did you read [Method 2](https://github.com/Maxmudjon/com.xiaomi-miio/blob/master/docs/obtain_token.md#method-2---obtain-xiaomi-gateway-device-token)?

**Comment by starkillerOG** [comment]
@hekm77 ah alright, now I see it, you are right.
Did not get that far ;) sorry.

**Comment by hekm77** [comment]
@starkillerOG   anyway, your instructions will remain in the issue. Somebody could use it.
