### ISSUE TITLE
Integrate in HomeAssistant

### ISSUE THREAD

**Issue by starkillerOG** [hekm77/homeassistant-config#8]
@hekm77 Do you have any plans to integrate your awesom component into the default [Xiaomi component](https://www.home-assistant.io/integrations/xiaomi_aqara/)?

If you make a PR to HomeAssistant I am sure a lot more people can benefit from this code!

**Comment by hekm77** [comment]
@starkillerOG 
No, I don't think so.
I'm not a developer.
The author of [python-miio](https://github.com/rytilahti/python-miio) could have done it, but apparently there are reasons.
Read the issues.

**Comment by starkillerOG** [comment]
@hekm77 Would you consider supporting [HACS](https://github.com/hacs/integration) to have easy install/updates?

did you write the code of this custom component or did you get it from somewhere else?

**Comment by starkillerOG** [comment]
@hekm77 Thank you for all your information.
Would you mind if I eventually make a PR (in HomeAssistant) to integrate your code into HomeAssistant?
I can do that on my own, so you would not have to help.

**Comment by hekm77** [comment]
@starkillerOG 
Of course I'm fine with it.

**Comment by starkillerOG** [comment]
For anyone looking for this in the future:
I added support for the Xiaomi Gateway Alarm in the python-miio platform (https://github.com/rytilahti/python-miio).
I am also busy with the HomeAssistant official integration of the Xiaomi Gateway Alarm and that schould be finished soon (only waiting on a version push of the python-miio library).
home-assistant/core#32091
